[package]
name = "kurobako"
version = "0.0.1"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
edition = "2018"
description = "A black-box optimization benchmarking framework"
homepage = "https://github.com/sile/kurobako"
repository = "https://github.com/sile/kurobako"
readme = "README.md"
license = "MIT"

[badges]
travis-ci = {repository = "sile/kurobako"}
codecov = {repository = "sile/kurobako"}

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
failure = "0.1"
rand = "0.6"
serde = "1"
serde_derive = "1"
serde_json = "1"
structopt = "0.2"
tempfile = "3"
yamakan = "0.0"
