[package]
name = "kurobako_core"
version = "0.1.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
serde = "1"
serde_derive = "1"
serde_json = "1"
structopt = "0.2"
yamakan = { git = "git://github.com/sile/yamakan.git" }
